### PR TITLE
speaker: error check pipeline setup

### LINKED ISSUE #39: Critical(s) in SpielSpeaker GStreamer pipeline
I believe these all boil down to a failure to link the `convert` and `sink` elements, although it might be a failure creating one of those causing the link problem.

This appears to be non-fatal, but it's an issue for Orca because PyGObject either bails or somehow propagates criticals as Python exceptions. Either way with this critical, `Spiel.Speaker.new_sync()` returns `None`.

```js
#!/usr/bin/env -S gjs -m

import GLib from 'gi://GLib';
import Gio from 'gi://Gio';
import Spiel from 'gi://Spiel';


const loop = GLib.MainLoop.new(null, false);
const speaker = Spiel.Speaker.new_sync(null);

for (const provider of speaker.providers) {
    console.log(`${provider.name} (${provider.well_known_name})`);
    for (const voice of provider.voices)
        console.log(`    ${voice.name} (${voice.languages})`);
}
```

Note `GI_TYPELIB_PATH` and `LD_LIBRARY_PATH` in the setup below, which are necessary if you have Spiel in e.g. `/usr/local`:

```c
gdb --args gjs -m spiel.js 
GNU gdb (Fedora Linux) 14.1-4.fc39
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gjs...
Reading symbols from /var/home/andrew/.cache/debuginfod_client/c90916466953ee52be407a2494a154ecb7e6b389/debuginfo...                                                                                                                         
(gdb) set environment G_DEBUG=fatal-warnings,fatal-criticals
(gdb) set environment GI_TYPELIB_PATH=/usr/local/lib64/girepository-1.0
(gdb) set environment LD_LIBRARY_PATH=/usr/local/lib64
(gdb) run
Starting program: /usr/bin/gjs -m spiel.js
[Thread debugging using libthread_db enabled]                                                                                                                                                                                                
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff3a006c0 (LWP 408928)]                                                                                                                                                                                                     
[Thread 0x7ffff3a006c0 (LWP 408928) exited]
[New Thread 0x7ffff3a006c0 (LWP 408929)]                                                                                                                                                                                                     
[New Thread 0x7ffff30006c0 (LWP 408930)]
[New Thread 0x7ffff26006c0 (LWP 408931)]
[New Thread 0x7ffff27ff6c0 (LWP 408932)]
[New Thread 0x7ffff1dff6c0 (LWP 408933)]
[New Thread 0x7ffff1c006c0 (LWP 408934)]
[New Thread 0x7ffff1a016c0 (LWP 408935)]
[New Thread 0x7ffff18026c0 (LWP 408936)]
[New Thread 0x7ffff16036c0 (LWP 408937)]
[New Thread 0x7ffff12006c0 (LWP 408938)]
[New Thread 0x7fffde8006c0 (LWP 408939)]                                                                                                                                                                                                     
                                                                                                                                                                                                                                             
(gjs:408925): GStreamer-CRITICAL **: 10:17:19.216: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (dest)' failed

Thread 1 "gjs" received signal SIGTRAP, Trace/breakpoint trap.
g_logv (log_domain=0x7ffff09a59ae "GStreamer", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fffffffcc00) at ../glib/gmessages.c:1423
1423              g_private_set (&g_log_depth, GUINT_TO_POINTER (depth));                                                                                                                                                                    
(gdb) bt
#0  g_logv (log_domain=0x7ffff09a59ae "GStreamer", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fffffffcc00) at ../glib/gmessages.c:1423
#1  0x00007ffff7d6a463 in g_log (log_domain=log_domain@entry=0x7ffff09a59ae "GStreamer", log_level=log_level@entry=G_LOG_LEVEL_CRITICAL, format=format@entry=0x7ffff7dd2280 "%s: assertion '%s' failed") at ../glib/gmessages.c:1461
#2  0x00007ffff7d6b6dd in g_return_if_fail_warning
    (log_domain=log_domain@entry=0x7ffff09a59ae "GStreamer", pretty_function=pretty_function@entry=0x7ffff09d30c0 <__func__.39> "gst_element_link_pads_full", expression=expression@entry=0x7ffff09d2082 "GST_IS_ELEMENT (dest)")
    at ../glib/gmessages.c:2930
#3  0x00007ffff098ae2a in gst_element_link_pads_full (src=0x55555581a8a0, srcpadname=0x0, dest=0x0, destpadname=0x0, flags=GST_PAD_LINK_CHECK_DEFAULT) at ../gst/gstutils.c:1816
#4  0x00007ffff30295d4 in _setup_pipeline (self=0x55555576c480, error=0x7fffffffcdd0) at ../subprojects/spiel/libspiel/spiel-speaker.c:508
#5  0x00007ffff3029924 in initable_init (initable=0x55555576c480, cancellable=0x0, error=0x7fffffffd2f0) at ../subprojects/spiel/libspiel/spiel-speaker.c:592
#6  0x00007ffff7b52a7c in g_initable_new_valist (object_type=<optimized out>, first_property_name=0x0, var_args=var_args@entry=0x7fffffffce40, cancellable=0x0, error=0x7fffffffd2f0) at ../gio/ginitable.c:250
#7  0x00007ffff7b52b6b in g_initable_new (object_type=<optimized out>, cancellable=<optimized out>, error=<optimized out>, first_property_name=<optimized out>) at ../gio/ginitable.c:164
#8  0x00007ffff3028c90 in spiel_speaker_new_sync (cancellable=0x0, error=0x7fffffffd2f0) at ../subprojects/spiel/libspiel/spiel-speaker.c:230
#9  0x00007ffff7a81056 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#10 0x00007ffff7a7d5ef in ffi_call_int (cif=cif@entry=0x55555576c080, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
#11 0x00007ffff7a803fe in ffi_call (cif=0x55555576c080, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>) at ../src/x86/ffi64.c:710
#12 0x00007ffff7ea193f in Gjs::Function::invoke (this=0x55555576c060, context=context@entry=0x5555555b6850, args=..., this_obj=..., r_value=r_value@entry=0x0) at ../gi/function.cpp:1058
#13 0x00007ffff7eac1d4 in Gjs::Function::call (context=0x5555555b6850, js_argc=<optimized out>, vp=<optimized out>) at ../gi/function.cpp:1236
#14 0x00007ffff692c778 in CallJSNative (args=..., reason=js::CallReason::Call, native=0x7ffff7eac0f0 <Gjs::Function::call(JSContext*, unsigned int, JS::Value*)>, cx=0x5555555b6850)
    at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:486
#15 js::InternalCallOrConstruct (cx=0x5555555b6850, args=..., construct=<optimized out>, reason=js::CallReason::Call) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:566
#16 0x00007ffff6920653 in InternalCall (reason=<optimized out>, args=<optimized out>, cx=<optimized out>) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:647
#17 js::CallFromStack (reason=<optimized out>, args=<optimized out>, cx=<optimized out>) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:652
#18 js::Interpret (cx=0x5555555b6850, state=...) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:3395
#19 0x00007ffff692c2bb in MaybeEnterInterpreterTrampoline (state=..., cx=0x5555555b6850) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:400
#20 js::RunScript (cx=0x5555555b6850, state=...) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:458
#21 0x00007ffff692d34f in js::ExecuteKernel (cx=<optimized out>, script=..., envChainArg=..., evalInFrame=..., result=...) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:845
#22 0x00007ffff696f691 in js::ModuleObject::execute (cx=<optimized out>, self=...) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/builtin/ModuleObject.cpp:1284
#23 0x00007ffff6a3707b in ExecuteAsyncModule (module=..., cx=0x5555555b6850) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Modules.cpp:1558
#24 InnerModuleEvaluation (cx=0x5555555b6850, module=..., stack=..., index=<optimized out>, indexOut=0x7fffffffda28) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Modules.cpp:1492
#25 0x00007ffff6a2a792 in js::ModuleEvaluate (result=..., moduleArg=..., cx=0x5555555b6850) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/dist/include/js/RootingAPI.h:1219
#26 JS::ModuleEvaluate (cx=0x5555555b6850, moduleRecord=..., moduleRecord@entry=..., rval=rval@entry=...) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Modules.cpp:163
#27 0x00007ffff7eea4eb in GjsContextPrivate::eval_module (error=0x7fffffffdd28, exit_status_p=0x7fffffffdd18 "", identifier=0x5555556e97d0 "file:///var/home/andrew/Testing/orca/spiel.js", this=0x5555555ad300)
    at /usr/include/mozjs-115/js/RootingAPI.h:1219
#28 gjs_context_eval_module (js_context=<optimized out>, identifier=0x5555556e97d0 "file:///var/home/andrew/Testing/orca/spiel.js", exit_code=0x7fffffffdd18 "", error=0x7fffffffdd28) at ../gjs/context.cpp:1324
#29 0x000055555555742a in define_argv_and_eval_script
    (filename=0x55555557e120 "spiel.js", len=<optimized out>, script=0x5555555a8710 "#!/usr/bin/env -S gjs -m\n\nimport GLib from 'gi://GLib';\nimport Gio from 'gi://Gio';\nimport Spiel from 'gi://Spiel';\n\n\nconst loop = GLib.MainLoop.new(null, false);\nconst speaker = Spiel.Speaker.new_syn"..., argv=<optimized out>, argc=<optimized out>, js_context=0x5555555ad480) at ../gjs/jsapi-util.h:163
#30 main (argc=<optimized out>, argv=<optimized out>) at ../gjs/console.cpp:393
(gdb) c
Continuing.
[Thread 0x7ffff12006c0 (LWP 408938) exited]

(gjs:408925): GLib-GObject-CRITICAL **: 10:25:43.807: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

Thread 1 "gjs" received signal SIGTRAP, Trace/breakpoint trap.
g_logv (log_domain=0x7ffff7ced030 "GLib-GObject", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fffffffcc70) at ../glib/gmessages.c:1423
1423		  g_private_set (&g_log_depth, GUINT_TO_POINTER (depth));
(gdb) bt
#0  g_logv (log_domain=0x7ffff7ced030 "GLib-GObject", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fffffffcc70) at ../glib/gmessages.c:1423
#1  0x00007ffff7d6a463 in g_log (log_domain=log_domain@entry=0x7ffff7ced030 "GLib-GObject", log_level=log_level@entry=G_LOG_LEVEL_CRITICAL, format=format@entry=0x7ffff7dd2280 "%s: assertion '%s' failed") at ../glib/gmessages.c:1461
#2  0x00007ffff7d6b6dd in g_return_if_fail_warning
    (log_domain=log_domain@entry=0x7ffff7ced030 "GLib-GObject", pretty_function=pretty_function@entry=0x7ffff7cf40d8 <__func__.27.lto_priv.0> "g_object_ref", expression=expression@entry=0x7ffff7cf1fdd "G_IS_OBJECT (object)")
    at ../glib/gmessages.c:2930
#3  0x00007ffff7cc8c7a in g_object_ref (_object=0x0) at ../gobject/gobject.c:3778
#4  0x00007ffff3029668 in _setup_pipeline (self=0x55555576c480, error=0x7fffffffcdd0) at ../subprojects/spiel/libspiel/spiel-speaker.c:519
#5  0x00007ffff3029924 in initable_init (initable=0x55555576c480, cancellable=0x0, error=0x7fffffffd2f0) at ../subprojects/spiel/libspiel/spiel-speaker.c:592
#6  0x00007ffff7b52a7c in g_initable_new_valist (object_type=<optimized out>, first_property_name=0x0, var_args=var_args@entry=0x7fffffffce40, cancellable=0x0, error=0x7fffffffd2f0) at ../gio/ginitable.c:250
#7  0x00007ffff7b52b6b in g_initable_new (object_type=<optimized out>, cancellable=<optimized out>, error=<optimized out>, first_property_name=<optimized out>) at ../gio/ginitable.c:164
#8  0x00007ffff3028c90 in spiel_speaker_new_sync (cancellable=0x0, error=0x7fffffffd2f0) at ../subprojects/spiel/libspiel/spiel-speaker.c:230
#9  0x00007ffff7a81056 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#10 0x00007ffff7a7d5ef in ffi_call_int (cif=cif@entry=0x55555576c080, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
#11 0x00007ffff7a803fe in ffi_call (cif=0x55555576c080, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>) at ../src/x86/ffi64.c:710
#12 0x00007ffff7ea193f in Gjs::Function::invoke (this=0x55555576c060, context=context@entry=0x5555555b6850, args=..., this_obj=..., r_value=r_value@entry=0x0) at ../gi/function.cpp:1058
#13 0x00007ffff7eac1d4 in Gjs::Function::call (context=0x5555555b6850, js_argc=<optimized out>, vp=<optimized out>) at ../gi/function.cpp:1236
#14 0x00007ffff692c778 in CallJSNative (args=..., reason=js::CallReason::Call, native=0x7ffff7eac0f0 <Gjs::Function::call(JSContext*, unsigned int, JS::Value*)>, cx=0x5555555b6850)
    at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:486
#15 js::InternalCallOrConstruct (cx=0x5555555b6850, args=..., construct=<optimized out>, reason=js::CallReason::Call) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:566
#16 0x00007ffff6920653 in InternalCall (reason=<optimized out>, args=<optimized out>, cx=<optimized out>) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:647
#17 js::CallFromStack (reason=<optimized out>, args=<optimized out>, cx=<optimized out>) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:652
#18 js::Interpret (cx=0x5555555b6850, state=...) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:3395
#19 0x00007ffff692c2bb in MaybeEnterInterpreterTrampoline (state=..., cx=0x5555555b6850) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:400
#20 js::RunScript (cx=0x5555555b6850, state=...) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:458
#21 0x00007ffff692d34f in js::ExecuteKernel (cx=<optimized out>, script=..., envChainArg=..., evalInFrame=..., result=...) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Interpreter.cpp:845
#22 0x00007ffff696f691 in js::ModuleObject::execute (cx=<optimized out>, self=...) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/builtin/ModuleObject.cpp:1284
#23 0x00007ffff6a3707b in ExecuteAsyncModule (module=..., cx=0x5555555b6850) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Modules.cpp:1558
#24 InnerModuleEvaluation (cx=0x5555555b6850, module=..., stack=..., index=<optimized out>, indexOut=0x7fffffffda28) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Modules.cpp:1492
#25 0x00007ffff6a2a792 in js::ModuleEvaluate (result=..., moduleArg=..., cx=0x5555555b6850) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/dist/include/js/RootingAPI.h:1219
#26 JS::ModuleEvaluate (cx=0x5555555b6850, moduleRecord=..., moduleRecord@entry=..., rval=rval@entry=...) at /usr/src/debug/mozjs115-115.7.0-1.fc39.x86_64/vm/Modules.cpp:163
#27 0x00007ffff7eea4eb in GjsContextPrivate::eval_module (error=0x7fffffffdd28, exit_status_p=0x7fffffffdd18 "", identifier=0x5555556e97d0 "file:///var/home/andrew/Testing/orca/spiel.js", this=0x5555555ad300)
    at /usr/include/mozjs-115/js/RootingAPI.h:1219
#28 gjs_context_eval_module (js_context=<optimized out>, identifier=0x5555556e97d0 "file:///var/home/andrew/Testing/orca/spiel.js", exit_code=0x7fffffffdd18 "", error=0x7fffffffdd28) at ../gjs/context.cpp:1324
#29 0x000055555555742a in define_argv_and_eval_script
    (filename=0x55555557e120 "spiel.js", len=<optimized out>, script=0x5555555a8710 "#!/usr/bin/env -S gjs -m\n\nimport GLib from 'gi://GLib';\nimport Gio from 'gi://Gio';\nimport Spiel from 'gi://Spiel';\n\n\nconst loop = GLib.MainLoop.new(null, false);\nconst speaker = Spiel.Speaker.new_syn"..., argv=<optimized out>, argc=<optimized out>, js_context=0x5555555ad480) at ../gjs/jsapi-util.h:163
#30 main (argc=<optimized out>, argv=<optimized out>) at ../gjs/console.cpp:393
(gdb) c
Continuing.
Gjs-Console-Message: 10:48:12.454: Piper (ai.piper.Speech.Provider)
Gjs-Console-Message: 10:48:12.455:     25hours_single (Tiếng Việt) (vi-VN)
Gjs-Console-Message: 10:48:12.456:     alan (English) (en-GB)

<spiel output continues, exits normally>
```

I've got a patch lined up that I think will solve the crash for Orca, although not sure about the cause yet :)

### PR DESCRIPTION
**Pull request by andyholmes**
Tighten up the pipeline setup with some more thorough error checking.

closes #39

### CODE REVIEW

File: libspiel/spiel-speaker.c [hunk 1]
```diff
@@ -498,14 +498,55 @@ static void
...
+      if (error != NULL && *error == NULL)
+        {
+          g_set_error_literal (error,
+                               GST_CORE_ERROR,
+                               GST_CORE_ERROR_FAILED,
+                               "Failed to create 'autoaudiosink' element; "
+                               "ensure GStreamer Good Plug-ins are installed");
+        }
+
+      gst_object_unref (gst_object_ref_sink (convert));
```
Comment (eeejay) [inline libspiel/spiel-speaker.c:530]: This is so weird but seems legit. I don't know why the factory returns floating references.

**Review by eeejay — COMMENTED** [review]
So with your testcase do you see failures in the pipeline creation? Is there something we should do to remedy them?

**Comment by andyholmes** [comment]
> So with your testcase do you see failures in the pipeline creation? Is there something we should do to remedy them?

I can cause a properly reported GError, but the crash and criticals are gone.

I was debugging Orca's build with a fresh container and build dependencies, but not `gstreamer1-plugins-good`. So the broken assumption was that `autoaudiosink` plugin was available.

Honestly I think it's probably rare for users to be missing that, but I mentioned it in the error message since that's the most likely failure. It should be good now.

File: libspiel/spiel-speaker.c (hunk 1 above)
Comment (andyholmes) [reply libspiel/spiel-speaker.c:530]: Yeah, it's definitely an odd thing to mix into MT-safe library. I half-expected that to crash, but there it is :)

I either forgot or never knew, but I guess functions can be organized for floating references to avoid big if-then chunks. Oh just in case, I'm pretty sure `g_autoptr (GstObject)` will not know to do a sink+unref.
